### ISSUE TITLE
R CMD check CEC documentation

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#519]

**Comment by igorsieradzki** [comment]
I've fixed CEC "docstrings" so that R check passes, but there were some issues someone from CEC needs to fix (`crtl+f` your name in cec.R and cec.plot.R should be enough but I'm going to list them anyway)

* undocumented parameter `params.function` in `CEC` function (all parameters needs to be documented!)
* undocumented parameter `method` in `plot.cec` function
* I've removed `log.iters` parameter form `CEC` function doc as it does not exist in code, should it?
* There was a docstring for function `nstart.cec` which does not exist in code, I've removed the docstring 
* this one is weird, you had docstring for function `predict.cec` but there was non such function, instead you passed 'anonymous' function to `setMethod`, like that: `setMethod("predict", "Rcpp_CecModel", function(args){...})`. I've created a functions `predict.cec` and moved that code there. Ran tests after that. 
* `@title` could be more informative then just a function name
* some (very simple) functions have no examples, I'm leaving to discussin whether they need them.

Please generate the documentation pdf and check if `CEC` docs are right and double check if prediction within `CEC` works as I've moved some code around.

**Disclaimer** This are only fixes to warnings given by `devtools::check_doc()`. Full check gives a lot of undocumented stuff, some of them is used in testing, other I'm not sure if should be documented, and some I don't really know how to document.
