### ISSUE TITLE
R CMD check GNG documentation

### ISSUE THREAD

**Issue by kudkudak** [gmum/gmum.r#520]

**Comment by igorsieradzki** [comment]
I've fixed GNG "docstrings" so that R check passes, but there were some issues @kudkudak  needs to fix (`crtl+f` your name in gng.R should be enough but I'm going to list them anyway)

* undocumented parameters `x, labels, max.edge.age, verbosity, seed` in `GNG` and `OptimizedGNG`
* undocumented parameter `community.detection.algorithm` in `predictCentroids`
* make sure the doc parameter `c` for `clustering.gng` is right (is it a GNG object?)
* there were double doc for `errorStatistics.gng`, was that intentional? I've removed one.
* there was a docstring for function `findClosest` whereas the function had a 's' (`findClosests`), I've added the 's', however I'm not sure which one is correct. 
* in `gng.visualize.R` there were 2 methods with "stub" docstrings (comments with `#'` above the declaration), those were not generating `.Rd` files. I've changed them to normal comments. Leave it as it is or write a full docstings for them. 
* `@title` could be more informative then just a function name (as is in `GNG` function doc)
* some examples have a comment (not mine) "TODO: Better example", it's for you to decide if they need one. 

Please generate the documentation pdf and check if all `GNG` docs are ok.

**Disclaimer** This are only fixes to warnings given by `devtools::check_doc()`. Full check gives a lot of undocumented stuff, some of them is used in testing, other I'm not sure if should be documented, and some I don't really know how to document.

**Comment by kudkudak** [comment]
Fantastic job!! Thanks, will look into this soon

**Comment by kudkudak** [comment]
* Document all user facing constants

**Comment by kudkudak** [comment]
For reference: https://github.com/gmum/gmum.r/blob/fix-r-check/R/gng.R#L988 , erase this setMethod.

**Comment by kudkudak** [comment]
I think I have covered everything, make new issue if there are additional problems
